#!/bin/sh /etc/rc.common

START=98
STOP=10
USE_PROCD=1

start_service() {
	local enabled mode iface setup freq ht_mode stream udp_listen udp_dest interval_ms

	config_load omega4-link
	config_get_bool enabled main enabled 0
	[ "$enabled" -eq 1 ] || return 0

	config_get mode main mode rx
	config_get iface main iface wlan0
	config_get_bool setup main setup 1
	config_get freq main freq 5180
	config_get ht_mode main ht_mode HT20
	config_get stream main stream 255
	config_get udp_listen main udp_listen 5601
	config_get udp_dest main udp_dest 127.0.0.1:5602
	config_get interval_ms main interval_ms 1000

	procd_open_instance
	procd_set_param command /usr/sbin/omega4-linkd --mode "$mode" --iface "$iface" --freq "$freq" --ht-mode "$ht_mode" --stream "$stream"
	[ "$setup" -eq 1 ] && procd_append_param command --setup
	[ "$mode" = "tx" ] && procd_append_param command --udp-listen "$udp_listen"
	[ "$mode" = "rx" ] && procd_append_param command --udp-dest "$udp_dest"
	[ "$mode" = "ping" ] && procd_append_param command --interval-ms "$interval_ms"
	procd_set_param respawn 5 5 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
